### ISSUE TITLE
Functionality for PBS

### ISSUE THREAD

**Issue by AdamWlodarczyk** [E-CAM/jobqueue_features#41]
Develop an cluster class for integration with PBS.

**Comment by AdamWlodarczyk** [comment]
Added funcionality for multiple nodes and mpi tasks in https://github.com/E-CAM/jobqueue_features/pull/52

It's still needs some adjustments but at the moment I think that some logic involved in computing mpi tasks number needs to be separated since logic differences between SLURM and PBS.

For example, each resource parameter in PBS is set for each chunk (representing the node).   

@ocaisa, should I keep updating the above draft or should it be changed to pull request as the first (or second) iteration of PBS funcionality?

**Comment by ocaisa** [comment]
@AdamWlodarczyk Let's talk about this later today, I don't fully understand why you might need new logic.

**Comment by ocaisa** [comment]
So as far as I understand, the most complex scenario you can have is:
```
#PBS -l select=2:ncpus=36:mpiprocs=4:ompthreads=9
```
which (from what I understand) is 2 nodes, with 4 MPI tasks per node and 9 OpenMP threads per MPI task. We can support this with the attributes that we have I think.

The one thing that is not clear to me is what happens when I need GPUs. This would require us to select the `accelerator` resource...does that *have* to be in the same line?
What I mean is, is
```
#PBS -l select=2:ncpus=36:mpiprocs=4:ompthreads=9
#PBS -l select=2:accelerator=True
```
the same as
```
#PBS -l select=2:ncpus=36:mpiprocs=4:ompthreads=9:accelerator=True
```
?

If it is not then we are going to have to get clever

**Comment by AdamWlodarczyk** [comment]
@ocaisa If you want to use GPUs there is an option i selection statement `ngpus`. It has to be added in `select=...` statement since it is used for each chunk (same as `ncpus`). 
The `accelerator=True` is also a must per selection statement since it is not a job-wide option (like `walltime`). Also, the `accelerator` option is used only for jobs designed to run on the Cray. I am not familiar with that at all.

**Comment by AdamWlodarczyk** [comment]
Looks like https://github.com/E-CAM/jobqueue_features/pull/52 meets above demands.
Let's talk about further works on next telco.
